// HTMLEdView.cpp : implementation file
//

#include "stdafx.h"
#include "Lolly.h"
#include "HTMLEdView.h"


// CHTMLEdView

IMPLEMENT_DYNCREATE(CHTMLEdView, CHtmlEditView)
BEGIN_DHTMLEDITING_CMDMAP(CHTMLEdView)
	DHTMLEDITING_CMD_ENTRY(ID_EDIT_CUT, IDM_CUT)
	DHTMLEDITING_CMD_ENTRY(ID_EDIT_COPY, IDM_COPY)
	DHTMLEDITING_CMD_ENTRY(ID_EDIT_PASTE, IDM_PASTE)
	DHTMLEDITING_CMD_ENTRY(ID_EDIT_UNDO, IDM_UNDO)
	DHTMLEDITING_CMD_ENTRY(ID_EDIT_SELECT_ALL, IDM_SELECTALL)
	//DHTMLEDITING_CMD_ENTRY(ID_EDIT_FONT, IDM_FONT)
	DHTMLEDITING_CMD_ENTRY(ID_TB_HE_INDENT, IDM_INDENT)
	DHTMLEDITING_CMD_ENTRY(ID_TB_HE_OUTDENT, IDM_OUTDENT)
	DHTMLEDITING_CMD_ENTRY(ID_TB_HE_IMAGE, IDM_IMAGE)
	DHTMLEDITING_CMD_ENTRY_FUNC(ID_TB_HE_ABSOLUTE, IDM_ABSOLUTE_POSITION, &CHTMLEdView::SetAbsPos)
	DHTMLEDITING_CMD_ENTRY_FUNC(ID_TB_HE_STATIC, IDM_ABSOLUTE_POSITION, &CHTMLEdView::SetStaticPos)
	DHTMLEDITING_CMD_ENTRY(ID_TB_HE_HYPERLINK, IDM_HYPERLINK)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_BOLD, IDM_BOLD, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_ITALIC, IDM_ITALIC, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_UNDERLINE, IDM_UNDERLINE, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_BULLETLIST, IDM_UNORDERLIST, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_NUMBERLIST, IDM_ORDERLIST, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_LEFTJUSTIFY, IDM_JUSTIFYLEFT, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_CENTERJUSTIFY, IDM_JUSTIFYCENTER, AFX_UI_ELEMTYPE_CHECBOX)
	DHTMLEDITING_CMD_ENTRY_TYPE(ID_TB_HE_RIGHTJUSTIFY, IDM_JUSTIFYRIGHT, AFX_UI_ELEMTYPE_CHECBOX)

END_DHTMLEDITING_CMDMAP()

CHTMLEdView::CHTMLEdView()
{

}

CHTMLEdView::~CHTMLEdView()
{
}

BEGIN_MESSAGE_MAP(CHTMLEdView, CHtmlEditView)
END_MESSAGE_MAP()


// CHTMLEdView diagnostics

#ifdef _DEBUG
void CHTMLEdView::AssertValid() const
{
	CHtmlEditView::AssertValid();
}

#ifndef _WIN32_WCE
void CHTMLEdView::Dump(CDumpContext& dc) const
{
	CHtmlEditView::Dump(dc);
}
#endif
#endif //_DEBUG


// CHTMLEdView message handlers

void CHTMLEdView::SetAbsPos(UINT)
{
	SetAbsolutePosition(true);
}

void CHTMLEdView::SetStaticPos(UINT)
{
	SetAbsolutePosition(false);
}
