//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Lolly.rc で使用
//
#define IDC_BUTTON_COPY                 3
#define IDC_BUTTON_COPYTEXT             3
#define IDCANCEL2                       3
#define IDCANCEL3                       4
#define IDCANCEL4                       5
#define IDCANCEL5                       6
#define IDCANCEL6                       7
#define IDCANCEL7                       8
#define IDCANCEL8                       9
#define IDCANCEL9                       10
#define IDCANCEL10                      11
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MFCAPPLICATION1_FORM        101
#define IDD_DATAGRID_FORM               101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_LollyTYPE                   130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_VS_2008         219
#define ID_VIEW_APPLOOK_WINDOWS_7       220
#define IDS_EDIT_MENU                   306
#define IDD_SELECT_UNITS                310
#define IDD_EXTRACT_WEB_DICT_OPTIONS    313
#define IDD_OPTIONS                     314
#define IDB_RECORD_MARKERS              314
#define IDD_SELECT_KANA                 316
#define IDD_SELECT_PICBOOK              317
#define IDD_EDIT_TRANS                  318
#define IDD_TEST                        319
#define IDD_NEW_WORDS                   320
#define IDR_TOOLBAR_WORDSUNITS          321
#define IDD_NEW_PHRASES                 321
#define IDR_TOOLBAR_WORDSLANG           322
#define IDD_FILTER                      322
#define IDR_TOOLBAR_WORDSBOOKS          323
#define IDD_REINDEX                     323
#define IDR_TOOLBAR_PHRASESUNITS        324
#define IDD_AUTOCORRECT_TEXT            324
#define IDR_TOOLBAR_PHRASESLANG         325
#define IDD_TEXT_TO_POST                325
#define IDR_TOOLBAR_AUXBOOKS            326
#define IDD_CONFIG_DICT                 326
#define IDR_TOOLBAR_AUXAUTOCORRECT      327
#define IDR_TOOLBAR_EXTRACTWEBDICT      328
#define IDR_TOOLBAR_WORDSEB             329
#define IDR_TOOLBAR_WEBBROWSER          330
#define IDR_TOOLBAR_PICBOOK             331
#define IDR_TOOLBAR_HTMLUNIT            332
#define IDR_TOOLBAR_WORDSATWILL         333
#define IDR_TOOLBAR_BLOGPOST            334
#define IDR_TOOLBAR_DICTS               335
#define IDR_POPUP_NAVIGATE              337
#define IDR_TOOLBAR_AUXDICTIONARIES     338
#define IDR_TOOLBAR_AUXPICBOOKS         339
#define IDR_TOOLBAR_AUXWEBEXTRACT       340
#define IDR_TOOLBAR_AUXWEBTEXT          341
#define IDR_TOOLBAR_AUXTODOLIST         342
#define ID_TB_RECORDPOS                 390
#define ID_TB_NAVIGATE_FORWARD          391
#define ID_TB_NAVIGATE_BACKWARD         392
#define ID_TB_NAVIGATE_ATRANDOM         393
#define ID_TB_RECORDCOUNT               400
#define ID_TB_DICTS                     402
#define ID_TB_OPEN                      403
#define ID_TB_SAVE                      404
#define ID_TB_FILTER_SET                406
#define ID_TB_FILTER_REMOVE             407
#define ID_TB_FILTER                    408
#define ID_TB_MOVEFIRST                 409
#define ID_TB_MOVEPREVIOUS              410
#define ID_TB_MOVENEXT                  411
#define ID_TB_MOVELAST                  412
#define ID_TB_ADDNEW                    413
#define ID_TB_DELETE                    414
#define ID_TB_REFRESH                   415
#define ID_TB_REINDEX                   416
#define ID_TB_EXTRACT_OVERWRITE         417
#define ID_TB_EXTRACT_APPEND            418
#define ID_TB_DELETE_TRANS              419
#define ID_TB_TIMER_NAVIGATE            420
#define ID_TB_LOOKUPBY_KANJI            421
#define ID_TB_LOOKUPBY_KANA             422
#define ID_TB_FIND_KANA                 423
#define ID_TB_MULTIADD                  424
#define ID_TB_WB_ADDRESS                425
#define ID_TB_WB_GO                     426
#define ID_TB_COPY_KANJI_KANA           427
#define ID_TB_HL_FILENAME               430
#define ID_TB_HL_BACK1                  431
#define ID_TB_HL_BACK2                  432
#define ID_TB_HL_REMOVEFORMAT           433
#define ID_TB_EDIT_TRANS                434
#define ID_TB_EWD_WORDLBL               435
#define ID_TB_EWD_LANGLBL               436
#define ID_TB_EWD_DICTLBL               437
#define ID_TB_EWD_WORD                  438
#define ID_TB_EWD_LANG                  439
#define ID_TB_EWD_DICT                  440
#define ID_TB_PB_BOOKNAME               441
#define ID_TB_PB_PAGENO                 442
#define ID_TB_PB_PAGECOUNT              443
#define ID_TB_PB_LINE1                  444
#define ID_TB_PB_LINE2                  445
#define ID_TB_PB_WRITE                  446
#define ID_TB_SPEAK                     447
#define ID_TB_KEEPSPEAK                 448
#define ID_TB_SPEAKTRANS                449
#define ID_TB_KEEPSPEAKTRANS            450
#define ID_TB_DICTS_OFFLINEALL          500
#define ID_TB_DICTS_OFFLINE1            501
#define ID_TB_DICTS_OFFLINE2            502
#define ID_TB_DICTS_OFFLINE3            503
#define ID_TB_DICTS_OFFLINE4            504
#define ID_TB_DICTS_OFFLINE5            505
#define ID_TB_DICTS_OFFLINE6            506
#define ID_TB_DICTS_OFFLINE7            507
#define ID_TB_DICTS_OFFLINE8            508
#define ID_TB_DICTS_OFFLINE9            509
#define ID_TB_DICTS_ONLINEALL           510
#define ID_TB_DICTS_ONLINE1             511
#define ID_TB_DICTS_ONLINE2             512
#define ID_TB_DICTS_ONLINE3             513
#define ID_TB_DICTS_ONLINE4             514
#define ID_TB_DICTS_ONLINE5             515
#define ID_TB_DICTS_ONLINE6             516
#define ID_TB_DICTS_ONLINE7             517
#define ID_TB_DICTS_ONLINE8             518
#define ID_TB_DICTS_ONLINE9             519
#define ID_TB_DICTS_LIVEALL             520
#define ID_TB_DICTS_LIVE1               521
#define ID_TB_DICTS_LIVE2               522
#define ID_TB_DICTS_LIVE3               523
#define ID_TB_DICTS_LIVE4               524
#define ID_TB_DICTS_LIVE5               525
#define ID_TB_DICTS_LIVE6               526
#define ID_TB_DICTS_LIVE7               527
#define ID_TB_DICTS_LIVE8               528
#define ID_TB_DICTS_LIVE9               529
#define ID_TB_DICTS_CUSTOM              530
#define ID_TB_DICTS_LOCAL               531
#define ID_TB_DICTS_SPECIAL             532
#define ID_TB_DICTS_CONJUGATOR          533
#define ID_TB_DICTS_WEB                 534
#define ID_TB_HE_BLOCKFMT               596
#define ID_TB_HE_COLOR                  597
#define ID_TB_HE_FONTNAME               598
#define ID_TB_HE_FONTSIZE               599
#define ID_TB_HE_INDENT                 600
#define ID_TB_HE_OUTDENT                601
#define ID_TB_HE_IMAGE                  602
#define ID_TB_HE_ABSOLUTE               603
#define ID_TB_HE_STATIC                 604
#define ID_TB_HE_HYPERLINK              605
#define ID_TB_HE_BOLD                   606
#define ID_TB_HE_ITALIC                 607
#define ID_TB_HE_UNDERLINE              608
#define ID_TB_HE_BULLETLIST             609
#define ID_TB_HE_NUMBERLIST             610
#define ID_TB_HE_LEFTJUSTIFY            611
#define ID_TB_HE_CENTERJUSTIFY          612
#define ID_TB_HE_RIGHTJUSTIFY           613
#define ID_TB_BP_TOGGLEVIEW             630
#define ID_TB_BP_LINEONLY               631
#define ID_TB_BP_NEWWORD                632
#define ID_TB_BP_NEWPATTERN             633
#define ID_TB_BP_PATTERNNAMES           634
#define ID_TB_BP_ORIGINAL               635
#define ID_TB_BP_DEFINITION             636
#define ID_TB_BP_TRANSLATION            637
#define ID_TB_BP_B                      638
#define ID_TB_BP_I                      639
#define ID_TB_WL_UP                     640
#define ID_TB_WL_DOWN                   641
#define ID_TB_DICTS_AVAILABLE           700
#define IDC_GRID_WORD                   1000
#define IDC_GRID_DICTNAME               1001
#define IDC_COMBO_BOOK                  1002
#define IDC_EDIT_UNITFROM               1003
#define IDC_SPIN_UNITFROM               1004
#define IDC_EDIT_UNITTO                 1005
#define IDC_SPIN_UNITTO                 1006
#define IDC_CHECK_ACTIVEINCLUDE         1007
#define IDC_STATIC_UNITINALLFROM        1008
#define IDC_COMBO_PARTFROM              1009
#define IDC_BOOKUNITS                   1010
#define IDC_COMBO_PARTTO                1010
#define IDC_LANG                        1011
#define IDC_STATIC_UNITINALLTO          1011
#define IDC_CHECKALLWORDS               1012
#define IDC_UNCHECKALLWORDS             1013
#define IDC_CHECKSELECTEDWORDS          1014
#define IDC_UNCHECKSELECTEDWORDS        1015
#define IDC_CHECKALLDICTS               1016
#define IDC_UNCHECKALLDICTS             1017
#define IDC_CHECKSELECTEDDICTS          1018
#define IDC_COMBO_LANG                  1019
#define IDC_UNCHECKSELECTEDDICTS        1019
#define IDC_OVERWRITE                   1020
#define IDC_KANAS                       1020
#define IDC_WORD                        1021
#define IDC_CHECK_TO                    1022
#define IDC_GRID_BOOK                   1023
#define IDC_EDIT_TRANS                  1024
#define IDC_ULTRALINGUA                 1025
#define IDC_LINGOES                     1026
#define IDC_LIST1                       1027
#define IDC_BUTTON1                     1028
#define IDC_EBTEST                      1029
#define IDC_EDIT_WORDS                  1030
#define IDC_EDIT_AFTER                  1031
#define IDC_EDIT_PHRASES_AND_TRANSLATIONS 1032
#define IDC_COMBO_SCOPE                 1033
#define IDC_COMBO_FILTER                1036
#define IDC_LIST_ITEMS                  1038
#define IDC_EDIT_BEFORE                 1040
#define IDC_COLOR_CELLTEXT              1041
#define IDC_COLOR_CELLBACK              1042
#define IDC_COLOR_CELLTEXT2             1043
#define IDC_COLOR_CELLBACK2             1044
#define IDC_STATIC_WORD                 1047
#define IDC_STATIC_PHRASE               1048
#define IDC_BUTTON_APPLYPOSTFORMAT      1050
#define IDC_EDIT_ORIG_TEXT              1051
#define IDC_EDIT_NEW_POST               1052
#define IDC_BUTTON_SAVE                 1053
#define IDC_LABEL1                      1054
#define IDC_LABEL2                      1055
#define IDC_LABEL3                      1056
#define IDC_COMBO_PARAGRAPH_END         1057
#define IDC_EDIT1                       1058
#define IDC_EDIT_NEW_WORD               1058
#define IDC_TREE1                       1059
#define IDC_TREE2                       1060
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_AUXILIARY_AUTOCORRECT        32772
#define ID_AUXILIARY_BOOKS              32773
#define ID_AUXILIARY_DICTIONARIES       32774
#define ID_AUXILIARY_PICBOOKS           32775
#define ID_AUXILIARY_WEBEXTRACT         32776
#define ID_AUXILIARY_WEBTEXT            32777
#define ID_LEARN_WORDS_UNITS            32800
#define ID_LEARN_WORDS_LANG             32801
#define ID_LEARN_WORDS_BOOKS            32802
#define ID_LEARN_PHRASES_UNITS          32803
#define ID_LEARN_PHRASES_LANG           32804
#define ID_WINDOW_CLOSEALL              32805
#define ID_LEARN_SELECTUNITS            32806
#define ID_TOOLS_EXTRACTWEBDICT         32807
#define ID_LEARN_WORDS_ATWILL           32808
#define ID_WORDHTML_PREVDICT            32809
#define ID_WORDHTML_NEXTDICT            32810
#define ID_WORDHTML_PREVWORD            32811
#define ID_WORDHTML_NEXTWORD            32812
#define ID_TOOLS_OPTIONS                32813
#define ID_TOOLS_WEBBROWSER             32822
#define ID_TOOLS_PICTUREBOOK            32825
#define ID_TOOLS_HTMLUNIT               32842
#define ID_FAVORITS_DUMMY               32846
#define ID_WINDOW_CLOSE                 32847
#define ID_TOOLS_TEST                   32848
#define ID_TTS_SPEAK                    32850
#define ID_TTS_STOPSPEAKING             32851
#define ID_TTS_SPEAKENGLISH             32855
#define ID_TTS_SPEAKCHINESE             32856
#define ID_WINDOW_NEW_WORDS_UNITS       32860
#define ID_WINDOW_NEW_WORDS_LANG        32861
#define ID_WINDOW_NEW_WORDS_BOOKS       32862
#define ID_WINDOW_NEW_PHRASES_UNITS     32863
#define ID_WINDOW_NEW_PHRASES_LANG      32864
#define ID_TOOLS_AUTOCORRECTTEXT        32885
#define ID_WINDOW_NEXT                  32898
#define ID_WINDOW_NEW_WORDS_ATWILL      32899
#define ID_TOOLS_NEWBLOGPOST            32907
#define ID_TOOLS_BLOGPOST               32910
#define ID_TOOLS_TEXT2POST              32911
#define ID_WINDOW_NEXTWINDOWS           32912
#define ID_LEARN_WORDS_UNITS_EB         32913
#define ID_LEARN_WORDS_ATWILL_EB        32914
#define ID_WINDOW_WORDS_UNITS_EB        32915
#define ID_WINDOW_NEW_WORDS_UNITS_EB    32916
#define ID_WINDOW_NEW_WORDS_ATWILL_EB   32917
#define ID_ACCELERATOR32920             32920
#define ID_NEWWINDOW_CURRENTWINDOW      32921
#define ID_WINDOW_NEW_CURRENT           32922

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32925
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           337
#endif
#endif
